<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EquipeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('equipe')->insert(array(
            array(
                'idEquipe' => 'e001',
                'nomEquipe' => 'Groupe folklorique du Bachkortostan',
                'identiteResponsable' => null,
                'adressePostale' => null,
                'nombrePersonnes' => 40,
                'nomPays' => 'Bachkirie',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e002',
                'nomEquipe' => 'Marina Prudencio Chavez',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 25,
                'nomPays' => 'Bolivie',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e003',
                'nomEquipe' => 'Nangola Bahia de Salvador',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 34,
                'nomPays' => 'Bresil',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e004',
                'nomEquipe' => 'Bizone de Kawarma',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 38,
                'nomPays' => 'Bulgarie',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e005',
                'nomEquipe' => 'Groupe folklorique camerounais',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 22,
                'nomPays' => 'Cameroun',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e006',
                'nomEquipe' => 'Syoung Yaru Mask Dance Group',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 29,
                'nomPays' => 'Coree du Sud',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e007',
                'nomEquipe' => 'Pipe Band',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 19,
                'nomPays' => 'Ecosse',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e008',
                'nomEquipe' => 'Aira da Pedra',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 5,
                'nomPays' => 'Espagne',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e009',
                'nomEquipe' => 'The Jersey Caledonian Pipe Band',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 21,
                'nomPays' => 'Jersey',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e010',
                'nomEquipe' => 'Groupe folklorique des Emirats',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 30,
                'nomPays' => 'Emirats arabes unis',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e011',
                'nomEquipe' => 'Groupe folklorique mexicain',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 38,
                'nomPays' => 'Mexique',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e012',
                'nomEquipe' => 'Groupe folklorique de Panama',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 22,
                'nomPays' => 'Panama',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e013',
                'nomEquipe' => 'Groupe folklorique papou',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 13,
                'nomPays' => 'Papouasie',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e014',
                'nomEquipe' => 'Paraguay Ete',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 26,
                'nomPays' => 'Paraguay',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e015',
                'nomEquipe' => 'La Tuque Bleue',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 8,
                'nomPays' => 'Quebec',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e016',
                'nomEquipe' => 'Ensemble Leissen de Oufa',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 40,
                'nomPays' => 'Republique de Bachkirie',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e017',
                'nomEquipe' => 'Groupe folklorique turc',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 40,
                'nomPays' => 'Turquie',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e018',
                'nomEquipe' => 'Groupe folklorique russe',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 43,
                'nomPays' => 'Russie',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e019',
                'nomEquipe' => 'Ruhunu Ballet du village de Kosgoda',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 27,
                'nomPays' => 'Sri Lanka',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e020',
                'nomEquipe' => 'LAlen',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 34,
                'nomPays' => 'France - Provence',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e021',
                'nomEquipe' => 'Lescolo Di Tourre',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 40,
                'nomPays' => 'France - Provence',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e022',
                'nomEquipe' => 'Deloubes Kevin',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 1,
                'nomPays' => 'France - Bretagne',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e023',
                'nomEquipe' => 'Daonie See',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 5,
                'nomPays' => 'France - Bretagne',
                'hebergement' => 'O',
              ),
              array(
                'idEquipe' => 'e024',
                'nomEquipe' => 'Boxty',
                'identiteResponsable' => null ,
                'adressePostale' => null ,
                'nombrePersonnes' => 5,
                'nomPays' => 'France - Bretagne',
                'hebergement' => 'O',
              ),
             array(
                 'idEquipe' => 'e025',
                 'nomEquipe' => 'Soeurs Chauvel',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 2,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'O',
             ),
             array(
                 'idEquipe' => 'e026',
                 'nomEquipe' => 'Cercle Gwik Alet',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
             array(
                 'idEquipe' => 'e027',
                 'nomEquipe' => 'Bagad Quic En Groigne',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
             array(
                 'idEquipe' => 'e028',
                 'nomEquipe' => 'Penn Treuz',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
             array(
                 'idEquipe' => 'e029',
                 'nomEquipe' => 'SavidEquipean Launay',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
                     ),
             array(
                 'idEquipe' => 'e030',
                 'nomEquipe' => 'Cercle Boked Er Lann',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
             array(
                 'idEquipe' => 'e031',
                 'nomEquipe' => 'Bagad Montfortais',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
             array(
                 'idEquipe' => 'e032',
                 'nomEquipe' => 'Vent de Noroise',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
             array(
                 'idEquipe' => 'e033',
                 'nomEquipe' => 'Cercle Strollad',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
             array(
                 'idEquipe' => 'e034',
                 'nomEquipe' => 'Bagad An Hanternoz',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
             array(
                 'idEquipe' => 'e035',
                 'nomEquipe' => 'Cercle Ar Vro Melenig',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
             array(
                 'idEquipe' => 'e036',
                 'nomEquipe' => 'Cercle An Abadenn Nevez',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
             array(
                 'idEquipe' => 'e037',
                 'nomEquipe' => 'Kerch Keltiek Roazhon',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
             array(
                 'idEquipe' => 'e038',
                 'nomEquipe' => 'Bagad Plougastel',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
             array(
                 'idEquipe' => 'e039',
                 'nomEquipe' => 'Bagad Nozeganed Bro Porh-Loeiz',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
             array(
                 'idEquipe' => 'e040',
                 'nomEquipe' => 'Bagad Nozeganed Bro Porh-Loeiz',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
              array(
                 'idEquipe' => 'e041',
                 'nomEquipe' => 'Jackie Molard Quartet',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
              array(
                 'idEquipe' => 'e042',
                 'nomEquipe' => 'Deomp',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
              array(
                 'idEquipe' => 'e043',
                 'nomEquipe' => 'Cercle Olivier de Clisson',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),
             array(
                 'idEquipe' => 'e044',
                 'nomEquipe' => 'Kan Tri',
                 'identiteResponsable' => null,
                 'adressePostale' => null,
                 'nombrePersonnes' => 0,
                 'nomPays' => 'France - Bretagne',
                 'hebergement' => 'N',
             ),  
          ));
    }
}
